### ISSUE TITLE
Html tag in select dropdown instead of quote symbol

### ISSUE THREAD

**Issue by onepood** [vegarringdal/Select2widgetAdvanced#3]
Html tag &quote; in select dropdown instead of " symbol. Please see screenshot.
In the value field it displayed correctly (also visible on screenshot).

This is very usable widget, thanks a lot for developing. 

![2015-01-23 1 02 18](https://cloud.githubusercontent.com/assets/10660864/5865630/e2505378-a29b-11e4-8cde-5a8bb133da65.png)

**Comment by vegarringdal** [comment]
I had similar issues with "/"

Its due to this part of select2...
https://github.com/vegarringdal/Select2widgetAdvanced/blob/master/select/select2.js#L381
Not sure what changing these would do, prb haveto do with the template part of select 2.

You could modify it and test.

Or if you can remove that symbol and use something else then in the dropdown only then you could do something like this


//temp hack for my app
try{
resultArray[i].name = resultArray[i].name.split('"').join("");
resultArray[i].desc = resultArray[i].desc.split('"').join("");
} catch(e){}

**Comment by vegarringdal** [comment]
overlook last comment.
just did a new commit where I fix the issue with escapeMarkup.
please download last version form grithub source and tell me if it works like you wanted.
(remeber to clear server/browser cache, so you have updated widget in browser when you try it)

**Comment by onepood** [comment]
Yes, it works! Thanks a lot.

**Comment by onepood** [comment]
I found that locales are available for the widget. Could you please explain how to use them or point me to a manual?

**Comment by vegarringdal** [comment]
I havent tried select2 with locales...
here is page to the source of select2:
https://github.com/ivaynberg/select2


If you like this widget then you should try:
https://github.com/vegarringdal/GridView
https://github.com/vegarringdal/InputText


video of a app Im working on with grid:
https://www.youtube.com/watch?v=zJ84mUxWTJk&feature=youtu.be

**Comment by vegarringdal** [comment]
I personally hate the waf grid....
mine got drag/drop columns, and locked columns, config in studio for height of header, row and footer etc etc,...
Footer also shows how many selected rows user have

both input and and grid have event onload to set decimal to use and dateformat, incase you wanto force a locale setting

**Comment by vegarringdal** [comment]
closing this issue, mail me on vegar.ringdal@gmail.com if you have more questions not related to bugs
